
' This file is used by Code Analysis to maintain SuppressMessage 
' attributes that are applied to this project.
' Project-level suppressions either have no target or are given 
' a specific target and scoped to a namespace, type, member, etc.

<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1401:P/Invokes should not be visible", Justification:="<Pending>", Scope:="type", Target:="~T:Outworldz.Form1")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification:="<Pending>", Scope:="member", Target:="~F:Outworldz.Form1.usa")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.Boot(Outworldz.RegionMaker,System.String,System.String)~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.Chart")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.CheckDefaultPorts")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.CheckForUpdates")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.CheckMysql~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.CheckPort(System.String,System.Int32)~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.ChooseRegion(System.Boolean)~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.ClearLogFiles")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.ConsoleCommand(System.String,System.String)~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.CopyWifi(System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.CreateService")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.CreateStopMySql")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.DelLibrary")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.DoGetHostAddresses(System.String)~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.Download~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.ExitHandlerPoll")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.GetEvents")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.GetFilesRecursive(System.String)~System.Collections.Generic.List{System.String}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.GetNewDnsName~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.IsApacheRunning~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.IsPrivateIP(System.String)~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.IsRobustRunning~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.KillApache")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.KillFiles(System.Collections.Generic.List{System.String})")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.KillFolder(System.Collections.Generic.List{System.String})")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.LoadLocalIAROAR")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.LoadOARContent(System.String)~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.Logger(System.String,System.String,System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.MakeBackup~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.OpenPorts~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.OpenRouterPorts~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.Opensimproto(System.Int32)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.ProbePublicPort~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.RegionListHTML")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.RegisterDNS~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.RegisterName(System.String)~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.RestoreDatabaseToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.RunDataSnapshot")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.ScanAgents")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.SetDefaultSims")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.SetFirewall")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.SetIAROARContent")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.SetPublicIP~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.SetQuickEditOff")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.SetupSearch")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.ShowDOSWindow(System.IntPtr,Outworldz.Form1.SHOWWINDOWENUM)~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.StartApache")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.StartIcecast")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.StartMySQL~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.StartOpensimulator~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.StartRobust~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.Startup")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.StopMysql")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.TestPublicLoopback~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.ToolStripMenuItem2_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.UpdaterGo")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.Viewlog(System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.WriteEvent(MySql.Data.MySqlClient.MySqlConnection,System.Collections.Generic.Dictionary{System.String,System.String})")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.FormRegion.CoordX_TextChanged(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.FormRegion.Coordy_TextChanged(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.FormRegion.DeleteButton_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.FormRegion.FilenameIsOK(System.String)~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.FormRegion.RegionChosen~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.FormRegion.WriteRegion(System.Int32)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Icecast.ShoutcastPortTextChanged(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Icecast.TextBox1_TextChanged(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.MysqlInterface.CheckPort(System.String,System.Int32)~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.MysqlInterface.QueryString(System.String)~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionList.AvatarView_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionList.LoadImage(System.String)~System.Drawing.Image")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionList.PickGroup~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionList.ShowAvatars")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionList.ShowRegions")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionList.StartStopEdit(System.Int32,System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionMaker.CheckPost")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionMaker.GetAllRegions")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionMaker.LargestPort~System.Int32")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionMaker.LowestPort~System.Int32")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionMaker.ParsePost(System.String,Outworldz.MySettings)~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionMaker.WriteRegionObject(System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~P:Outworldz.RegionMaker.ProcessID(System.Int32)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~P:Outworldz.RegionMaker.RegionPort(System.Int32)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~P:Outworldz.RegionMaker.Timer(System.Int32)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification:="<Pending>", Scope:="type", Target:="~T:Outworldz.RegionMaker.JSONresult")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.CleanDLLs")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.IsPrivateIP(System.String)~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.SaveInventoryIARToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.SetIAROARContent")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.Viewlog(System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.ListViewItemComparer.Compare(System.Object,System.Object)~System.Int32")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionMaker.CheckPost")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionMaker.GetAllRegions")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.CrashDetector.Find")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionMaker.UpdateAllRegionPorts")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.FormCritical.Button1_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.RegionMaker.RegionListHTML(Outworldz.MySettings)~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.AdvancedForm.Form1_FormClosing(System.Object,System.Windows.Forms.FormClosingEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.MySettings.GetMySetting(System.String,System.String)~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.MySettings.LoadMyIni")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.MySettings.LoadOtherIni(System.String,System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.MySettings.SaveApacheINI(System.String,System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.MySettings.SaveOtherINI")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.MySettings.SaveSettings")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.MySettings.SetMyIni(System.String,System.String,System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.MySettings.SetOtherIni(System.String,System.String,System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~P:Outworldz.MySettings.SCPortBase")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~P:Outworldz.MySettings.SCPortBase1")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.Zap(System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.MySettings.SetApacheIni(System.String,System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.DoRegions")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.Form1.SetIniData~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.FormRegions.RegionButton1_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.ClrCache.WipeImage")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.ClrCache.WipeBakes")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.ClrCache.WipeAssets")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.ClrCache.WipeScripts")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.ClrCache.WipeMesh")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.ScreenPos.LoadXYIni")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.UPnp.LocalIP~System.String")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.UploadImage.PostContentUploadFile")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.UploadImage.RequestStreamAvailable(System.IAsyncResult)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.ScreenPos.SaveFormSettings")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.ScreenPos.SetXYIni(System.String,System.String,System.String)")>
<Assembly: CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope:="member", Target:="Outworldz.Form1.#GetEvents()")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification:="<Pending>", Scope:="member", Target:="~M:Outworldz.UPnp.IsPrivateIP(System.String)~System.Boolean")>