'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Outworldz.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apache.
        '''</summary>
        Friend ReadOnly Property Apache() As String
            Get
                Return ResourceManager.GetString("Apache", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apache Webserver.
        '''</summary>
        Friend ReadOnly Property Apache_Webserver() As String
            Get
                Return ResourceManager.GetString("Apache_Webserver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apache Webserver + Search and Map.
        '''</summary>
        Friend ReadOnly Property ApacheWebServer() As String
            Get
                Return ResourceManager.GetString("ApacheWebServer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Arrow2Left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrow2Left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Arrow2Right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrow2Right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto Backup.
        '''</summary>
        Friend ReadOnly Property Auto_Backup() As String
            Get
                Return ResourceManager.GetString("Auto_Backup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup.
        '''</summary>
        Friend ReadOnly Property Backup() As String
            Get
                Return ResourceManager.GetString("Backup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup Custom Web Pages.
        '''</summary>
        Friend ReadOnly Property Backup_Custom() As String
            Get
                Return ResourceManager.GetString("Backup_Custom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup Data Files.
        '''</summary>
        Friend ReadOnly Property Backup_Data_Files() As String
            Get
                Return ResourceManager.GetString("Backup_Data_Files", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup Folder.
        '''</summary>
        Friend ReadOnly Property Backup_Folder() As String
            Get
                Return ResourceManager.GetString("Backup_Folder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup FSAssets folder.
        '''</summary>
        Friend ReadOnly Property Backup_FSAssets() As String
            Get
                Return ResourceManager.GetString("Backup_FSAssets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup Mysql Data folder.
        '''</summary>
        Friend ReadOnly Property Backup_Mysql() As String
            Get
                Return ResourceManager.GetString("Backup_Mysql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup Region INI files.
        '''</summary>
        Friend ReadOnly Property Backup_Region() As String
            Get
                Return ResourceManager.GetString("Backup_Region", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to set up your Backup Schedule.
        '''</summary>
        Friend ReadOnly Property Backup_Schedule() As String
            Get
                Return ResourceManager.GetString("Backup_Schedule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup Settings.
        '''</summary>
        Friend ReadOnly Property Backup_Settings() As String
            Get
                Return ResourceManager.GetString("Backup_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Best() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Best", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Better() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Better", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bird Flock Size.
        '''</summary>
        Friend ReadOnly Property Bird_Flock_Size() As String
            Get
                Return ResourceManager.GetString("Bird_Flock_Size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click for Help on Birds.
        '''</summary>
        Friend ReadOnly Property Bird_help() As String
            Get
                Return ResourceManager.GetString("Bird_help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load Bird IAR.
        '''</summary>
        Friend ReadOnly Property Bird_IAR() As String
            Get
                Return ResourceManager.GetString("Bird_IAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bird Module.
        '''</summary>
        Friend ReadOnly Property Bird_Module() As String
            Get
                Return ResourceManager.GetString("Bird_Module", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bird Settings.
        '''</summary>
        Friend ReadOnly Property Bird_Settings() As String
            Get
                Return ResourceManager.GetString("Bird_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blankbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blankbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Border Size (default=25.0).
        '''</summary>
        Friend ReadOnly Property Border_Size() As String
            Get
                Return ResourceManager.GetString("Border_Size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property box_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property box_tall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box_tall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BuiltbyFred() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuiltbyFred", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Caches.
        '''</summary>
        Friend ReadOnly Property Caches() As String
            Get
                Return ResourceManager.GetString("Caches", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property check2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to set up the Birds module.
        '''</summary>
        Friend ReadOnly Property Click_Birds() As String
            Get
                Return ResourceManager.GetString("Click_Birds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to set up Caches for scripts, assets, and images.
        '''</summary>
        Friend ReadOnly Property Click_Caches() As String
            Get
                Return ResourceManager.GetString("Click_Caches", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to set up Currency.
        '''</summary>
        Friend ReadOnly Property Click_Currency() As String
            Get
                Return ResourceManager.GetString("Click_Currency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to set up the Database.
        '''</summary>
        Friend ReadOnly Property Click_Database() As String
            Get
                Return ResourceManager.GetString("Click_Database", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to Enable Hypergrid or change DNS Name.
        '''</summary>
        Friend ReadOnly Property Click_HG() As String
            Get
                Return ResourceManager.GetString("Click_HG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to Setup Shoutcast/Icecast.
        '''</summary>
        Friend ReadOnly Property Click_Icecast() As String
            Get
                Return ResourceManager.GetString("Click_Icecast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to set up Maps.
        '''</summary>
        Friend ReadOnly Property Click_Maps() As String
            Get
                Return ResourceManager.GetString("Click_Maps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to set up default Physics.
        '''</summary>
        Friend ReadOnly Property Click_Physics() As String
            Get
                Return ResourceManager.GetString("Click_Physics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to set up your Ports.
        '''</summary>
        Friend ReadOnly Property Click_Ports() As String
            Get
                Return ResourceManager.GetString("Click_Ports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to set up Publicity at Hyperica.com.
        '''</summary>
        Friend ReadOnly Property Click_Publicity() As String
            Get
                Return ResourceManager.GetString("Click_Publicity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to set up  Regions.
        '''</summary>
        Friend ReadOnly Property Click_Regions() As String
            Get
                Return ResourceManager.GetString("Click_Regions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to Set up Start/Stop.
        '''</summary>
        Friend ReadOnly Property Click_Restart() As String
            Get
                Return ResourceManager.GetString("Click_Restart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to set up Servers such as Grid, Region, OsGrid or Metro.
        '''</summary>
        Friend ReadOnly Property Click_Server() As String
            Get
                Return ResourceManager.GetString("Click_Server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to set up Tides.
        '''</summary>
        Friend ReadOnly Property Click_Tides() As String
            Get
                Return ResourceManager.GetString("Click_Tides", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to change the folder.
        '''</summary>
        Friend ReadOnly Property Click_to_change_the_folder() As String
            Get
                Return ResourceManager.GetString("Click_to_change_the_folder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to Request Voice Service.
        '''</summary>
        Friend ReadOnly Property Click_to_Request_Voice_Service() As String
            Get
                Return ResourceManager.GetString("Click_to_Request_Voice_Service", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to Set up Vivox Voice.
        '''</summary>
        Friend ReadOnly Property Click_Voice() As String
            Get
                Return ResourceManager.GetString("Click_Voice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to set up your Web Control Panel.
        '''</summary>
        Friend ReadOnly Property Click_Web() As String
            Get
                Return ResourceManager.GetString("Click_Web", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClicktoInsertPhoto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClicktoInsertPhoto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Common Settings.
        '''</summary>
        Friend ReadOnly Property Common_Settings() As String
            Get
                Return ResourceManager.GetString("Common_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cube_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cube_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property cubes_blue() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cubes_blue", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property data() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Setup.
        '''</summary>
        Friend ReadOnly Property Database_Setup() As String
            Get
                Return ResourceManager.GetString("Database_Setup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This determines whether the module does anything.
        '''</summary>
        Friend ReadOnly Property Determines() As String
            Get
                Return ResourceManager.GetString("Determines", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property disk_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property disk_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property disk_yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk_yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property disks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_connection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_connection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_dirty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_dirty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_view() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_view", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_view1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_view1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DreamGrid.
        '''</summary>
        Friend ReadOnly Property DreamGrid() As String
            Get
                Return ResourceManager.GetString("DreamGrid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property earth_network() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("earth_network", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable.
        '''</summary>
        Friend ReadOnly Property Enable() As String
            Get
                Return ResourceManager.GetString("Enable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable Bird Module?.
        '''</summary>
        Friend ReadOnly Property Enable_Birds() As String
            Get
                Return ResourceManager.GetString("Enable_Birds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable Events.
        '''</summary>
        Friend ReadOnly Property Enable_Events() As String
            Get
                Return ResourceManager.GetString("Enable_Events", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable Search.
        '''</summary>
        Friend ReadOnly Property Enable_Search() As String
            Get
                Return ResourceManager.GetString("Enable_Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable Apache Web server.
        '''</summary>
        Friend ReadOnly Property EnableApache() As String
            Get
                Return ResourceManager.GetString("EnableApache", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enabled.
        '''</summary>
        Friend ReadOnly Property Enabled() As String
            Get
                Return ResourceManager.GetString("Enabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property error_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exit_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend ReadOnly Property Exit_text() As String
            Get
                Return ResourceManager.GetString("Exit_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export SQL file.
        '''</summary>
        Friend ReadOnly Property Export_SQL_file() As String
            Get
                Return ResourceManager.GetString("Export_SQL_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gear_run() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gear_run", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gloebits Currency.
        '''</summary>
        Friend ReadOnly Property Gloebits_Currency() As String
            Get
                Return ResourceManager.GetString("Gloebits_Currency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Good() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Good", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend ReadOnly Property Help() As String
            Get
                Return ResourceManager.GetString("Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to How close to the edges of things can we get without being worried?.
        '''</summary>
        Friend ReadOnly Property How_Close() As String
            Get
                Return ResourceManager.GetString("How_Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to How far away from other birds we would like to stay?.
        '''</summary>
        Friend ReadOnly Property How_Far() As String
            Get
                Return ResourceManager.GetString("How_Far", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to How far in meters each bird can travel per update.
        '''</summary>
        Friend ReadOnly Property How_Far_Travel() As String
            Get
                Return ResourceManager.GetString("How_Far_Travel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to How high are we allowed to flock?.
        '''</summary>
        Friend ReadOnly Property How_High() As String
            Get
                Return ResourceManager.GetString("How_High", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to How long to keep the backups. After this time in days, the oldest get deleted..
        '''</summary>
        Friend ReadOnly Property How_Long() As String
            Get
                Return ResourceManager.GetString("How_Long", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to How long Opensim runs before an Auto backup occurs.
        '''</summary>
        Friend ReadOnly Property How_Long_runs() As String
            Get
                Return ResourceManager.GetString("How_Long_runs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hypergrid DNS Name.
        '''</summary>
        Friend ReadOnly Property Hypergrid() As String
            Get
                Return ResourceManager.GetString("Hypergrid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Icecast/Shoutcast.
        '''</summary>
        Friend ReadOnly Property Icecast_Shoutcast() As String
            Get
                Return ResourceManager.GetString("Icecast_Shoutcast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If enabled, Opensim will save OARS  after running this long.
        '''</summary>
        Friend ReadOnly Property If_Enabled_Save_Oars() As String
            Get
                Return ResourceManager.GetString("If_Enabled_Save_Oars", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Install C++ Runtime.
        '''</summary>
        Friend ReadOnly Property InstallRuntime() As String
            Get
                Return ResourceManager.GetString("InstallRuntime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interval.
        '''</summary>
        Friend ReadOnly Property Interval() As String
            Get
                Return ResourceManager.GetString("Interval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keep for days.
        '''</summary>
        Friend ReadOnly Property Keep_for_Days() As String
            Get
                Return ResourceManager.GetString("Keep_for_Days", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Local Search.
        '''</summary>
        Friend ReadOnly Property Local_Search() As String
            Get
                Return ResourceManager.GetString("Local_Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property map_1_9510_10006_objects() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("map_1_9510_10006_objects", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maps.
        '''</summary>
        Friend ReadOnly Property Maps() As String
            Get
                Return ResourceManager.GetString("Maps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The maximum acceleration allowed to the current velocity of the bird.
        '''</summary>
        Friend ReadOnly Property Max_Accel() As String
            Get
                Return ResourceManager.GetString("Max_Accel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max distance for other birds to be considered in the same flock.
        '''</summary>
        Friend ReadOnly Property Max_Dist() As String
            Get
                Return ResourceManager.GetString("Max_Dist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max Force (default=0.2).
        '''</summary>
        Friend ReadOnly Property Max_Force() As String
            Get
                Return ResourceManager.GetString("Max_Force", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max Height (default=45.0).
        '''</summary>
        Friend ReadOnly Property Max_Heght() As String
            Get
                Return ResourceManager.GetString("Max_Heght", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max Speed (default=1.0).
        '''</summary>
        Friend ReadOnly Property Max_Speed() As String
            Get
                Return ResourceManager.GetString("Max_Speed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property media_fast_forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_fast_forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property media_pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property media_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property media_rewind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_rewind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property media_stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property media_stop_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_stop_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property media_stop_red1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media_stop_red1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nav_plain_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nav_plain_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nav_plain_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nav_plain_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nav_plain_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nav_plain_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property navigate_check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigate_check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property navigate_cross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigate_cross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property navigate_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigate_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property navigate_down2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigate_down2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property navigate_minus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigate_minus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property navigate_plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigate_plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property navigate_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigate_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property navigate_up2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigate_up2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Neighbor Distance (default=25.0).
        '''</summary>
        Friend ReadOnly Property Neighbor() As String
            Get
                Return ResourceManager.GetString("Neighbor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Ports.
        '''</summary>
        Friend ReadOnly Property Network_Ports() As String
            Get
                Return ResourceManager.GetString("Network_Ports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Normally set to  OutworldzFiles/AutoBackup folder with &apos;AutoBackup&apos;.  Click to change the folder..
        '''</summary>
        Friend ReadOnly Property Normally_Set() As String
            Get
                Return ResourceManager.GetString("Normally_Set", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The number of birds to flock.
        '''</summary>
        Friend ReadOnly Property Num_Birds() As String
            Get
                Return ResourceManager.GetString("Num_Birds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OfflineMap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OfflineMap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property package() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("package", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend ReadOnly Property Password() As String
            Get
                Return ResourceManager.GetString("Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pdf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Physics.
        '''</summary>
        Friend ReadOnly Property Physics() As String
            Get
                Return ResourceManager.GetString("Physics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prim Name (default=SeaGull1).
        '''</summary>
        Friend ReadOnly Property Prim_Name() As String
            Get
                Return ResourceManager.GetString("Prim_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property printer3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Publicity.
        '''</summary>
        Friend ReadOnly Property Publicity() As String
            Get
                Return ResourceManager.GetString("Publicity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property question_and_answer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("question_and_answer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property recycle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("recycle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Regions.
        '''</summary>
        Friend ReadOnly Property Regions() As String
            Get
                Return ResourceManager.GetString("Regions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property replace2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("replace2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restart Settings.
        '''</summary>
        Friend ReadOnly Property Restart_Settings() As String
            Get
                Return ResourceManager.GetString("Restart_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run As A Service.
        '''</summary>
        Friend ReadOnly Property RunasAService() As String
            Get
                Return ResourceManager.GetString("RunasAService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend ReadOnly Property Search() As String
            Get
                Return ResourceManager.GetString("Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search All Grids.
        '''</summary>
        Friend ReadOnly Property Search_All_Grids() As String
            Get
                Return ResourceManager.GetString("Search_All_Grids", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Desired Separation (default=5.0).
        '''</summary>
        Friend ReadOnly Property Separation() As String
            Get
                Return ResourceManager.GetString("Separation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Server_Client() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Server_Client", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server Type.
        '''</summary>
        Friend ReadOnly Property Server_Type() As String
            Get
                Return ResourceManager.GetString("Server_Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to set up your Terms of Service.
        '''</summary>
        Friend ReadOnly Property Setup_TOS() As String
            Get
                Return ResourceManager.GetString("Setup_TOS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Setup Voice Service.
        '''</summary>
        Friend ReadOnly Property Setup_Voice_Service() As String
            Get
                Return ResourceManager.GetString("Setup_Voice_Service", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Simple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Simple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skip.
        '''</summary>
        Friend ReadOnly Property Skip() As String
            Get
                Return ResourceManager.GetString("Skip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start.
        '''</summary>
        Friend ReadOnly Property Start_text() As String
            Get
                Return ResourceManager.GetString("Start_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting Up ....
        '''</summary>
        Friend ReadOnly Property Starting() As String
            Get
                Return ResourceManager.GetString("Starting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop.
        '''</summary>
        Friend ReadOnly Property Stop_text() As String
            Get
                Return ResourceManager.GetString("Stop_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ... Stopped.
        '''</summary>
        Friend ReadOnly Property Stopped() As String
            Get
                Return ResourceManager.GetString("Stopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System Backup.
        '''</summary>
        Friend ReadOnly Property System_Backup() As String
            Get
                Return ResourceManager.GetString("System_Backup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terms of Service.
        '''</summary>
        Friend ReadOnly Property Terms_of_Service() As String
            Get
                Return ResourceManager.GetString("Terms_of_Service", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_align_justified() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_align_justified", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_marked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_marked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tides.
        '''</summary>
        Friend ReadOnly Property Tides() As String
            Get
                Return ResourceManager.GetString("Tides", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tolerance (default=25.0).
        '''</summary>
        Friend ReadOnly Property Tolerance() As String
            Get
                Return ResourceManager.GetString("Tolerance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property transform() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transform", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user1_into() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user1_into", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User ID.
        '''</summary>
        Friend ReadOnly Property UserID() As String
            Get
                Return ResourceManager.GetString("UserID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property users1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property users2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property users3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version.
        '''</summary>
        Friend ReadOnly Property Version() As String
            Get
                Return ResourceManager.GetString("Version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vivox Voice.
        '''</summary>
        Friend ReadOnly Property Vivox_Voice() As String
            Get
                Return ResourceManager.GetString("Vivox_Voice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voice.
        '''</summary>
        Friend ReadOnly Property Voice() As String
            Get
                Return ResourceManager.GetString("Voice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property water() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Web Control Panel.
        '''</summary>
        Friend ReadOnly Property Web() As String
            Get
                Return ResourceManager.GetString("Web", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Web Port (80, or 8000).
        '''</summary>
        Friend ReadOnly Property Web_Port() As String
            Get
                Return ResourceManager.GetString("Web_Port", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Which channel do birds listen to for in-world commands.  Negative numbers cannot be used by humans.
        '''</summary>
        Friend ReadOnly Property Which_Channel() As String
            Get
                Return ResourceManager.GetString("Which_Channel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property window_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property window_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property window_environment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_environment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
